"use client"

import * as React from "react"
import { addPropertyControls, ControlType } from "framer"

/* -----------------------------------------------------------
   BlogHub — editorial blog hub for frenchmaison.co.uk
   - Uniform responsive card grid, newest post first
   - Fetches all articles from a generated JSON file in the repo

   DATA SOURCE
   A Framer code component can't read a CMS collection directly,
   so the 17 Articles are pre-exported to `articles.json` at the
   root of the framer-components repo and fetched at runtime from
   raw.githubusercontent.com (default `sourceUrl` below).

   articles.json is produced by `scripts/gen_articles.py`, which
   reads the published site's search index (title, excerpt, date,
   author, read time, url) and each post's og:image (cover).
   ➜ When you add/edit posts in the CMS and republish, re-run that
   script and commit the refreshed articles.json — no component
   change needed.

   The `posts` prop seeds initial state so the canvas shows content
   instantly; the fetch then replaces it with the live list.
----------------------------------------------------------- */

const ARTICLES_URL =
    "https://raw.githubusercontent.com/tomcummings26-beep/framer-components/main/articles.json"

const SERIF_STACK =
    '"Cormorant Garamond", "Libre Baskerville", Georgia, "Times New Roman", serif'

const SANS_STACK =
    '"Inter", "Inter var", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif'

// ✅ Image helper.
// Blog covers are Framer CMS images on framerusercontent.com — our Cloudflare
// proxy (img.frenchmaison.co.uk) 403s on that host, and framerusercontent only
// honours `scale-down-to`, so resize those natively and skip the proxy.
// Everything else goes through the Cloudflare proxy like the other components.
const getOptimizedImage = (url: string, width: number, quality = 80) => {
    if (!url) return ""

    if (url.includes("framerusercontent.com")) {
        const dpr =
            typeof window !== "undefined"
                ? Math.min(window.devicePixelRatio || 1, 2)
                : 1
        const target = Math.min(2048, Math.round(width * dpr))
        const clean = url.split("?")[0]
        return `${clean}?scale-down-to=${target}`
    }

    const base = "https://img.frenchmaison.co.uk/"

    const standardWidths = [400, 800, 1200, 1600, 2000]
    const roundToNearest = (target: number) =>
        standardWidths.reduce((prev, curr) =>
            Math.abs(curr - target) < Math.abs(prev - target) ? curr : prev
        )

    const dpr =
        typeof window !== "undefined"
            ? Math.min(window.devicePixelRatio || 1, 2)
            : 1

    const finalWidth = roundToNearest(Math.round(width * dpr))
    return `${base}?url=${encodeURIComponent(url)}&width=${finalWidth}&quality=${quality}`
}

type Post = {
    title: string
    excerpt: string
    cover: string
    date: string
    href: string
    author?: string
    readTime?: string
    featured?: boolean
}

// Baked article list — kept in sync with articles.json by
// scripts/gen_articles.py. This is the component's initial render data, so all
// post links appear in Framer's statically-rendered HTML and are crawlable by
// search engines / Screaming Frog without running JS. The runtime fetch then
// refreshes it client-side.
// prettier-ignore
const BAKED_ARTICLES: Post[] = [
    // ARTICLES:START — generated by scripts/gen_articles.py; do not edit by hand
    {
        title: "What's Included in a French Villa Rental? UK Guide 2026",
        excerpt: "From taxe de séjour to end-clean, linen and wifi: what a French villa rental price actually covers, and what UK travellers pay on top in 2026.",
        cover: "https://framerusercontent.com/images/glRRotWL58ipIVcepDX2xGqAs.jpg",
        date: "15 Jun 2026",
        href: "/blog/whats-included-french-villa-rental",
        author: "The French Maison Team",
        readTime: "9 min read",
    },
    {
        title: "How to Host a Wedding at a French Villa or Chateau",
        excerpt: "Plan your French villa or chateau wedding: legal requirements for UK couples, venue types, supplier costs and realistic timelines from 12 months out.",
        cover: "https://framerusercontent.com/images/wsM2EUShWSjzYlQMHnHqbr6678.jpg",
        date: "12 Jun 2026",
        href: "/blog/how-to-host-wedding-french-villa-chateau",
        author: "The French Maison Team",
        readTime: "11 min read",
    },
    {
        title: "Best Time to Visit the Côte d'Azur for a Villa Holiday",
        excerpt: "The best time for a Côte d'Azur villa is early-to-mid June or September: 25°C highs, 22°C sea, and around £267 per head saved against peak August.",
        cover: "https://framerusercontent.com/images/tsrzb3ICizVBW9UBMdvW7UKZao.jpg",
        date: "10 Jun 2026",
        href: "/blog/best-time-visit-cote-dazur-villa",
        author: "The French Maison Team",
        readTime: "9 min read",
    },
    {
        title: "Best Month to Rent a Villa in Provence (2026 Guide)",
        excerpt: "September wins on weather, value and harvest energy, but UK families have better moves. A month-by-month guide to Provence villa timing, with Météo-France data.",
        cover: "https://framerusercontent.com/images/vymR9K8LllubrHuqK1rlvmUEWJU.jpg",
        date: "8 Jun 2026",
        href: "/blog/best-month-villa-provence",
        author: "The French Maison Team",
        readTime: "9 min read",
    },
    {
        title: "7 Days in the Dordogne: A Family Villa Itinerary",
        excerpt: "Plan a family villa week in the Périgord Noir: Sarlat market, Lascaux IV, river canoeing and the castle circuit, all within 30 minutes of your base.",
        cover: "https://framerusercontent.com/images/Iv5K3ARpoLJfNx0EjFvR0lANO6c.jpg",
        date: "5 Jun 2026",
        href: "/blog/7-days-dordogne-family-itinerary",
        author: "The French Maison Team",
        readTime: "11 min read",
    },
    {
        title: "7-Day Provence Itinerary from a Villa Base",
        excerpt: "Plan a 7-day Provence villa itinerary from a Luberon base: markets, Chateauneuf wines, Saint-Remy and Cassis, with drive times and weekly costs.",
        cover: "https://framerusercontent.com/images/sTxPZm2e7oN9Q6jTGIybvzovRZ8.jpg",
        date: "3 Jun 2026",
        href: "/blog/7-day-provence-itinerary-villa-base",
        author: "The French Maison Team",
        readTime: "12 min read",
    },
    {
        title: "Best Villas in the Luberon: Hilltop Villages & Pool Views",
        excerpt: "French Maison Luberon villas near Bonnieux, Ménerbes, Roussillon and Apt: pool details, weekly prices from £1,140 and how to get there from the UK.",
        cover: "https://framerusercontent.com/images/asLw3Au4tgh2XQ8uykff4VrL8g.jpg",
        date: "1 Jun 2026",
        href: "/blog/best-villas-luberon-hilltop-villages",
        author: "The French Maison Team",
        readTime: "11 min read",
    },
    {
        title: "The 12 Best Villas Near Sarlat, Dordogne | French Maison",
        excerpt: "Villas near Sarlat, Dordogne: private-pool family homes within 20 minutes of the Périgord Noir's finest medieval market town, from £1,800 a week.",
        cover: "https://framerusercontent.com/images/MONk5RcylBU2YE7JPhKYK3GTLE.jpg",
        date: "29 May 2026",
        href: "/blog/best-villas-near-sarlat-dordogne",
        author: "The French Maison Team",
        readTime: "11 min read",
    },
    {
        title: "Loire Valley Chateau & Villa Holidays 2026 | Guide",
        excerpt: "Loire Valley chateau holidays for UK travellers: best areas, when to go, costs, top chateaux, wine and cycling, plus how to get there from the UK in 2026.",
        cover: "https://framerusercontent.com/images/KHchF1tjHvEDzbgzjn0BPoggM.jpg",
        date: "27 May 2026",
        href: "/blog/loire-valley-chateau-villa-holidays",
        author: "The French Maison Team",
        readTime: "13 min read",
    },
    {
        title: "Dordogne Family Villa Holidays: A Périgord Guide 2026",
        excerpt: "Plan a Dordogne family villa holiday in the Périgord: best areas, castles, canoeing, costs and UK travel tips for Sarlat and Périgord Noir in 2026.",
        cover: "https://framerusercontent.com/images/dM1rklDnl82FzzJsAu8XYeDw.jpg",
        date: "25 May 2026",
        href: "/blog/dordogne-villa-holidays-family",
        author: "The French Maison Team",
        readTime: "14 min read",
    },
    {
        title: "Côte d'Azur Villa Holidays: French Riviera Guide 2026",
        excerpt: "Plan your Côte d'Azur villa holiday: compare Nice, Cannes, Antibes, St Tropez and Cap Ferrat, with costs, climate data and UK travel tips for 2026.",
        cover: "https://framerusercontent.com/images/sXfCfVo8yr0K6gFTFRIfZiHd8.jpg",
        date: "22 May 2026",
        href: "/blog/cote-dazur-villa-holidays",
        author: "The French Maison Team",
        readTime: "14 min read",
    },
    {
        title: "Provence Villa Holidays 2026: UK Guide",
        excerpt: "Plan a Provence villa holiday from the UK in 2026: best sub-regions, pool villa costs from £1,200 a week, when to go and how to drive from Calais.",
        cover: "https://framerusercontent.com/images/3SZqzZ88J5DBHz0Qrah8b7VAkw.jpg",
        date: "20 May 2026",
        href: "/blog/provence-villa-holidays-2026",
        author: "The French Maison Team",
        readTime: "16 min read",
    },
    {
        title: "Driving to a French Villa from the UK | 2026 Route Guide",
        excerpt: "Planning to drive to a villa in France in 2026? This guide covers Eurotunnel vs ferry, post-Brexit documents, drive times to every region, French road rules and total cost.",
        cover: "https://framerusercontent.com/images/D8xbYqYZnxyitD63YaJ9aoaEA.jpg",
        date: "19 May 2026",
        href: "/blog/driving-to-france-villa-uk",
        author: "The French Maison Team",
        readTime: "13 min read",
    },
    {
        title: "How Much Does a Villa in France Cost in 2026? Full Guide",
        excerpt: "Villa holiday costs in France 2026: real prices by region and season. Dordogne from £1,200/week, Provence from £1,800. Budget guide for UK travellers.",
        cover: "https://framerusercontent.com/images/dM1rklDnl82FzzJsAu8XYeDw.jpg",
        date: "15 May 2026",
        href: "/blog/how-much-does-a-villa-in-france-cost",
        author: "The French Maison Team",
        readTime: "12 min read",
    },
    {
        title: "Villa, Gîte, Château or Cottage: A UK Guide",
        excerpt: "What is the difference between a French villa, gîte, château and cottage? A UK guide to classification, weekly costs from £600, and choosing the right type.",
        cover: "https://framerusercontent.com/images/V9fx3n2c7Vx3yaamlMWu9sfO8.jpg",
        date: "13 May 2026",
        href: "/blog/villa-gite-chateau-cottage-difference",
        author: "The French Maison Team",
        readTime: "11 min read",
    },
    {
        title: "Villa Holidays in France 2026/27 | UK Guide",
        excerpt: "A UK guide to villa holidays in France for 2026/27. Regions, costs from £700 to £3,600 a week, when to go, ferry routes and post-Brexit rules.",
        cover: "https://framerusercontent.com/images/ulJk6uvWngLg0SmdIgEZcMr7e4.jpg",
        date: "7 May 2026",
        href: "/blog/villa-holidays-france-2026",
        author: "The French Maison Team",
        readTime: "18 min read",
    },
    {
        title: "Family Villa Holidays in France | UK Parents' Guide",
        excerpt: "Planning a family villa holiday in France from the UK? Our guide covers regions, pool safety, school holiday timing, costs from £1,200 per week, and travel logistics.",
        cover: "https://framerusercontent.com/images/QCmnLnwBQfEfOIFJc95wKhqXoyw.jpg",
        date: "6 May 2026",
        href: "/blog/family-villa-holidays-france",
        author: "The French Maison Team",
        readTime: "16 min read",
    },
    // ARTICLES:END
]

type Props = {
    sourceUrl: string
    posts: Post[]
    heading: string
    intro: string
    maxPosts: number
    columns: "auto" | "2" | "3" | "4"
    maxWidth: number
    radius: number
    topPadding: number
    bottomPadding: number
    background: string
    cardBackground: string
    borderColor: string
    headingColor: string
    textColor: string
    mutedColor: string
    linkColor: string
}

export default function BlogHub(props: Props) {
    const {
        sourceUrl,
        posts,
        heading,
        intro,
        maxPosts,
        columns,
        maxWidth,
        radius,
        topPadding,
        bottomPadding,
        background,
        cardBackground,
        borderColor,
        headingColor,
        textColor,
        mutedColor,
        linkColor,
    } = props

    // Seed with the prop posts so the canvas renders instantly,
    // then replace with the live fetched list.
    const [loaded, setLoaded] = React.useState<Post[]>(posts || [])

    React.useEffect(() => {
        if (!sourceUrl) return
        let cancelled = false
        async function load() {
            try {
                const res = await fetch(sourceUrl, { cache: "no-store" })
                if (!res.ok) return
                const data: Post[] = await res.json()
                if (!cancelled && Array.isArray(data) && data.length) {
                    setLoaded(data)
                }
            } catch (err) {
                console.error("BlogHub: failed to load articles", err)
            }
        }
        load()
        return () => {
            cancelled = true
        }
    }, [sourceUrl])

    // Newest first (articles.json is pre-sorted, but stay defensive),
    // then optional cap.
    const visiblePosts = React.useMemo(() => {
        const list = [...(loaded || [])].sort((a, b) => {
            const ta = new Date(a.date).getTime()
            const tb = new Date(b.date).getTime()
            if (isNaN(ta) || isNaN(tb)) return 0
            return tb - ta
        })
        return maxPosts > 0 ? list.slice(0, maxPosts) : list
    }, [loaded, maxPosts])

    const gridTemplate =
        columns === "auto"
            ? "repeat(auto-fit, minmax(300px, 1fr))"
            : `repeat(${columns}, 1fr)`

    return (
        <section
            aria-labelledby="fm-blog-heading"
            style={{
                width: "100%",
                background,
                padding: `${topPadding}px 20px ${bottomPadding}px`,
            }}
        >
            <div
                style={{ maxWidth, margin: "0 auto", display: "grid", gap: 28 }}
            >
                {/* Header */}
                <div style={{ display: "grid", gap: 12 }}>
                    <h2 id="fm-blog-heading" style={{ margin: 0 }}>
                        <span
                            style={{
                                display: "block",
                                fontSize: "clamp(28px, 4vw, 42px)",
                                lineHeight: 1.05,
                                letterSpacing: "-0.03em",
                                color: headingColor,
                                fontFamily: SERIF_STACK,
                                fontWeight: 500,
                            }}
                        >
                            {heading}
                        </span>
                    </h2>
                    {intro ? (
                        <p
                            style={{
                                margin: 0,
                                fontSize: 17,
                                lineHeight: 1.8,
                                color: mutedColor,
                                fontFamily: SANS_STACK,
                                maxWidth: 760,
                            }}
                        >
                            {intro}
                        </p>
                    ) : null}
                </div>

                {/* Grid */}
                {visiblePosts.length > 0 ? (
                    <div
                        style={{
                            display: "grid",
                            gridTemplateColumns: gridTemplate,
                            gap: 24,
                        }}
                    >
                        {visiblePosts.map((post, i) => (
                            <BlogCard
                                key={`${post.href}-${i}`}
                                post={post}
                                index={i}
                                cardBackground={cardBackground}
                                borderColor={borderColor}
                                headingColor={headingColor}
                                textColor={textColor}
                                mutedColor={mutedColor}
                                linkColor={linkColor}
                                radius={radius}
                            />
                        ))}
                    </div>
                ) : (
                    <p
                        style={{
                            margin: 0,
                            fontSize: 16,
                            lineHeight: 1.7,
                            color: mutedColor,
                            fontFamily: SANS_STACK,
                        }}
                    >
                        Loading articles…
                    </p>
                )}
            </div>
        </section>
    )
}

/* -----------------------------
   BlogCard
----------------------------- */
function BlogCard({
    post,
    index,
    cardBackground,
    borderColor,
    headingColor,
    textColor,
    mutedColor,
    linkColor,
    radius,
}: {
    post: Post
    index: number
    cardBackground: string
    borderColor: string
    headingColor: string
    textColor: string
    mutedColor: string
    linkColor: string
    radius: number
}) {
    return (
        <a
            href={post.href}
            style={{
                display: "flex",
                flexDirection: "column",
                background: cardBackground,
                border: `1px solid ${borderColor}`,
                borderRadius: radius,
                overflow: "hidden",
                textDecoration: "none",
                boxShadow: post.featured
                    ? "0 12px 30px rgba(21, 56, 82, 0.08)"
                    : "none",
            }}
        >
            {/* Cover */}
            <div
                style={{
                    position: "relative",
                    width: "100%",
                    aspectRatio: "16 / 10",
                    background: "#EDF1F4",
                    overflow: "hidden",
                }}
            >
                {post.cover ? (
                    <img
                        src={getOptimizedImage(post.cover, 800)}
                        alt={post.title}
                        width="800"
                        height="500"
                        decoding="async"
                        loading={index === 0 ? "eager" : "lazy"}
                        style={{
                            width: "100%",
                            height: "100%",
                            objectFit: "cover",
                            display: "block",
                        }}
                    />
                ) : null}
            </div>

            {/* Body */}
            <div
                style={{
                    padding: 22,
                    display: "grid",
                    gap: 12,
                    flex: 1,
                }}
            >
                <div
                    style={{
                        display: "flex",
                        flexWrap: "wrap",
                        gap: 8,
                        alignItems: "center",
                        fontFamily: SANS_STACK,
                        fontSize: 13,
                        color: mutedColor,
                    }}
                >
                    {post.date ? <span>{post.date}</span> : null}
                    {post.date && (post.author || post.readTime) ? (
                        <span aria-hidden>•</span>
                    ) : null}
                    {post.author ? <span>{post.author}</span> : null}
                    {post.author && post.readTime ? (
                        <span aria-hidden>•</span>
                    ) : null}
                    {post.readTime ? <span>{post.readTime}</span> : null}
                </div>

                <h3 style={{ margin: 0 }}>
                    <span
                        style={{
                            display: "block",
                            fontSize: 24,
                            lineHeight: 1.15,
                            letterSpacing: "-0.02em",
                            color: headingColor,
                            fontFamily: SERIF_STACK,
                            fontWeight: 500,
                        }}
                    >
                        {post.title}
                    </span>
                </h3>

                {post.excerpt ? (
                    <p
                        style={{
                            margin: 0,
                            fontSize: 15,
                            lineHeight: 1.7,
                            color: textColor,
                            fontFamily: SANS_STACK,
                        }}
                    >
                        {post.excerpt}
                    </p>
                ) : null}

                <span
                    style={{
                        marginTop: "auto",
                        color: linkColor,
                        fontFamily: SANS_STACK,
                        fontSize: 15,
                        fontWeight: 600,
                    }}
                >
                    Read article →
                </span>
            </div>
        </a>
    )
}

BlogHub.defaultProps = {
    sourceUrl: ARTICLES_URL,
    heading: "The French Maison Journal",
    intro: "Stories, guides and inspiration for your next villa holiday in France — from regional travel notes to seasonal highlights.",
    maxPosts: 0,
    columns: "auto",
    maxWidth: 1200,
    radius: 24,
    topPadding: 40,
    bottomPadding: 40,
    background: "#FFFFFF",
    cardBackground: "#F8FAFC",
    borderColor: "#E2E8F0",
    headingColor: "#153852",
    textColor: "#243648",
    mutedColor: "#5E6B78",
    linkColor: "#153852",
    posts: BAKED_ARTICLES,
}

addPropertyControls(BlogHub, {
    sourceUrl: {
        type: ControlType.String,
        title: "Source URL",
        description: "articles.json feed (raw GitHub)",
    },
    heading: { type: ControlType.String, title: "Heading" },
    intro: {
        type: ControlType.String,
        title: "Intro",
        displayTextArea: true,
    },
    maxPosts: {
        type: ControlType.Number,
        title: "Max Posts",
        min: 0,
        max: 60,
        step: 1,
        description: "0 shows all posts",
    },
    columns: {
        type: ControlType.Enum,
        title: "Columns",
        options: ["auto", "2", "3", "4"],
        optionTitles: ["Auto", "2", "3", "4"],
        displaySegmentedControl: true,
    },
    maxWidth: {
        type: ControlType.Number,
        title: "Max Width",
        min: 800,
        max: 1400,
        step: 10,
    },
    radius: {
        type: ControlType.Number,
        title: "Radius",
        min: 0,
        max: 40,
        step: 1,
    },
    topPadding: {
        type: ControlType.Number,
        title: "Top Pad",
        min: 0,
        max: 120,
        step: 4,
    },
    bottomPadding: {
        type: ControlType.Number,
        title: "Bottom Pad",
        min: 0,
        max: 120,
        step: 4,
    },
    background: { type: ControlType.Color, title: "Background" },
    cardBackground: { type: ControlType.Color, title: "Card BG" },
    borderColor: { type: ControlType.Color, title: "Border" },
    headingColor: { type: ControlType.Color, title: "Heading" },
    textColor: { type: ControlType.Color, title: "Text" },
    mutedColor: { type: ControlType.Color, title: "Muted" },
    linkColor: { type: ControlType.Color, title: "Link" },
})
